# Generated by Django 5.2 on 2025-04-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.FloatField(null=True),
        ),
    ]
